version: '3.8'
services:
  api_handler:
    build:
      context: .
      dockerfile: ./dockerfiles/Backend.dockerfile
    restart: always
    working_dir: "/app"
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    volumes:
      - ./api_handler:/app
    command: python manage.py runserver 0.0.0.0:8000

  db:
    image: "postgres:${POSTGRES_VERSION}"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local